# Generated by Django 4.2.3 on 2023-08-14 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoss', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes_model',
            old_name='notes',
            new_name='note',
        ),
    ]
