# Generated by Django 4.2.3 on 2023-08-14 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoss', '0002_rename_notes_notes_model_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes_model',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
